### ISSUE TITLE
在Android中上传图片报错”java.net.ProtocolException: unexpected end of stream“

### ISSUE THREAD

**Issue by Hclmaster** [aliyun/aliyun-oss-android-sdk#104]
我在安卓中使用了OSS服务，我是先将android的bitmap格式转化为byte格式再进行上传，但是发生了错误。
我的调用代码如下所示：
```java
// OSSClient只初始化了一次
credentialProvider = new OSSPlainTextAKSKCredentialProvider(ACCESS_KEY_ID, ACCESS_KEY_SECRET);
client = new OSSClient(getApplicationContext(), ENDPOINT, credentialProvider);

try {
                String object_key = FOLDER + "camera_img.jpg";
                PutObjectRequest put = new PutObjectRequest(BUCKET_NAME, object_key, byteArray);
                System.out.println("PutObjectRequest这里出现了问题????");

                PutObjectResult putResult = client.putObject(put);
                Log.d("PutObject", "UploadSuccess");
                Log.d("ETag", putResult.getETag());
                Log.d("RequestId", putResult.getRequestId());

                // ###########################################
                // 保存上传图片的文件路径
                img_url = "https://tf-img-classifier.oss-cn-shanghai.aliyuncs.com/camera_img.jpg";
                System.out.println("---------------->成功!");

                flag = 1;
            } catch (ClientException e) {
                // 本地异常如网络异常等
                e.printStackTrace();
                System.out.println("---------------->失败!");
            } catch (ServiceException e) {
                // 服务异常
                Log.e("RequestId", e.getRequestId());
                Log.e("ErrorCode", e.getErrorCode());
                Log.e("HostId", e.getHostId());
                Log.e("RawMessage", e.getRawMessage());
                System.out.println("---------------->异常!");
            }
            if(flag == 1){
                // ##################################################
                // 4.1号添加
                // Mqtt发布到broker中去
                //mqttHelper.publishMessage(img_url);
                try {
                    MqttClient sampleClient = new MqttClient(mqttHelper.serverUri, mqttHelper.clientId, null);
                    //sampleClient.setCallback(new MyMqttCallback());

                    // 创建连接选择
                    MqttConnectOptions connOpts = getMqttConnectOptions(mqttHelper.username,mqttHelper.password);
                    System.out.println("Connecting to broker: "+mqttHelper.serverUri);

                    sampleClient.connect(connOpts);
                    System.out.println("Connected");

                    //sampleClient.subscribe(mqttHelper.publishTopic);

                    //在另一个线程中发送消息
                    Thread thread = new Thread(() -> {
                        try {
                            publishMsg(mqttHelper.publishTopic, img_url, sampleClient);
                        } catch (MqttException e) {
                            e.printStackTrace();
                        }
                    });
                    thread.start();

                    thread.join();
                    //断开服务连接
                    sampleClient.disconnect();
                    System.out.println("Disconnected");
                } catch (MqttException me) {
                    System.out.println("reason "+me.getReasonCode());
                    System.out.println("msg "+me.getMessage());
                    System.out.println("loc "+me.getLocalizedMessage());
                    System.out.println("cause "+me.getCause());
                    System.out.println("excep "+me);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        }
```
报错信息如下: 
```java
W/oss-android-api: type=1400 audit(0.0:426): avc: denied { write } for name="perfd" dev="mmcblk2p18" ino=1318 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:shell_data_file:s0 tclass=dir permissive=0
W/oss-android-api: type=1400 audit(0.0:427): avc: denied { write } for name="perfd" dev="mmcblk2p18" ino=1318 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:shell_data_file:s0 tclass=dir permissive=0
W/System.err: java.net.ProtocolException: unexpected end of stream
W/System.err:     at okhttp3.internal.http.Http1xStream$FixedLengthSink.close(Http1xStream.java:294)
W/System.err:     at okio.RealBufferedSink.close(RealBufferedSink.java:236)
W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:48)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at com.android.tools.profiler.agent.okhttp.OkHttp3Interceptor.intercept(OkHttp3Interceptor.java:52)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
W/System.err:     at okhttp3.RealCall.execute(RealCall.java:60)
W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:174)
W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:44)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err:     at java.lang.Thread.run(Thread.java:764)
W/System.err: java.net.ProtocolException: unexpected end of stream
W/System.err:     at okhttp3.internal.http.Http1xStream$FixedLengthSink.close(Http1xStream.java:294)
W/System.err:     at okio.RealBufferedSink.close(RealBufferedSink.java:236)
W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:48)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at com.android.tools.profiler.agent.okhttp.OkHttp3Interceptor.intercept(OkHttp3Interceptor.java:52)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
W/System.err:     at okhttp3.RealCall.execute(RealCall.java:60)
W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:174)
W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:243)
W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:44)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err:     at java.lang.Thread.run(Thread.java:764)
```
```java
W/System.err: com.alibaba.sdk.android.oss.ClientException: unexpected end of stream
W/System.err: [ErrorMessage]: unexpected end of stream
W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:197)
W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:243)
W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:243)
W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:44)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err:     at java.lang.Thread.run(Thread.java:764)
W/System.err: Caused by: java.net.ProtocolException: unexpected end of stream
W/System.err:     at okhttp3.internal.http.Http1xStream$FixedLengthSink.close(Http1xStream.java:294)
W/System.err:     at okio.RealBufferedSink.close(RealBufferedSink.java:236)
W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:48)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at com.android.tools.profiler.agent.okhttp.OkHttp3Interceptor.intercept(OkHttp3Interceptor.java:52)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
W/System.err:     at okhttp3.RealCall.execute(RealCall.java:60)
W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:174)
W/System.err: 	... 7 more
```

这个问题已经困扰我好几天了，请麻烦解决一下，谢谢！

**Comment by 1019272778** [comment]
@Hclmaster 你好，抱歉回复晚了。我们测试用byte数组上传是没问题的。不知道您现在解决问题了吗？

**Comment by Hclmaster** [comment]
已解决，该问题并不是经常发生，当时我是重启了一下编译器就不再报错了。

**Comment by burgessjp** [comment]
这个问题我也遇到了，只是部分手机上会出现（必现）。看到希望能回复一下。

```
 W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:167)
        at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:236)
        at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:43)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by q365719562** [comment]
我也出现了这个问题，在华为mate10 9.0的系统没问题，但是在三星 6.0的系统会有这个问题。不知道咋整

**Comment by Saqrag** [comment]
@HannahNick 问题解决了吗？
