### ISSUE TITLE
问题描述 ： Gradle配置以后不能同步，某文件找不到，在浏览器也打不开无法下载。

### ISSUE THREAD

**Issue by infsafe** [aliyun/aliyun-oss-android-sdk#107]
最新版本2.8.0
org.gradle.internal.resource.transport.http.HttpRequestException: Could not GET 'https://jcenter.bintray.com/com/aliyun/ams/alicloud-android-ut/maven-metadata.xml'.
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performRequest(HttpClientHelper.java:96)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performRawGet(HttpClientHelper.java:80)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performGet(HttpClientHelper.java:84)
	at org.gradle.internal.resource.transport.http.HttpResourceAccessor.openResource(HttpResourceAccessor.java:43)
	at org.gradle.internal.resource.transport.http.HttpResourceAccessor.openResource(HttpResourceAccessor.java:29)
	at

**Comment by 1019272778** [comment]
alicloud-android-ut 这个不是oss android sdk的路径
正确路径如下
<metadata>
  <groupId>com.aliyun.dpa</groupId>
  <artifactId>oss-android-sdk</artifactId>
  <version>2.8.0</version>
  <versioning>
    <latest>2.8.0</latest>
    <release>2.8.0</release>
    <versions>
      <version>2.2.3</version>
      <version>2.2.5</version>
      <version>2.4.0</version>
      <version>2.4.1.2</version>
      <version>2.4.2</version>
      <version>2.4.3</version>
      <version>2.4.4</version>
      <version>2.4.5</version>
      <version>2.5.0</version>
      <version>2.6.0</version>
      <version>2.7.0</version>
      <version>2.7.1</version>
      <version>2.7.3</version>
      <version>2.8.0</version>
    </versions>
    <lastUpdated>20180322015653</lastUpdated>
  </versioning>
</metadata>
