### ISSUE TITLE
上传文件崩溃

### ISSUE THREAD

**Issue by andoop** [aliyun/aliyun-oss-android-sdk#154]
`com.alibaba.sdk.android.oss.ClientException: Expected a quoted string (position:DOCDECL @1:50 in java.io.InputStreamReader@99aba86) 
org.xmlpull.v1.XmlPullParserException: Expected a quoted string (position:DOCDECL @1:50 in java.io.InputStreamReader@99aba86) 
	at com.alibaba.sdk.android.oss.internal.ResponseParsers.parseResponseErrorXML(ResponseParsers.java:585)
	at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:212)
	at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:44)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: org.xmlpull.v1.XmlPullParserException: Expected a quoted string (position:DOCDECL @1:50 in java.io.InputStreamReader@99aba86) 
	at org.kxml2.io.KXmlParser.readQuotedId(KXmlParser.java:671)
	at org.kxml2.io.KXmlParser.readExternalId(KXmlParser.java:650)
	at org.kxml2.io.KXmlParser.readDoctype(KXmlParser.java:591)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:421)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
	at com.alibaba.sdk.android.oss.internal.ResponseParsers.parseResponseErrorXML(ResponseParsers.java:576)
	... 6 more

`

**Comment by andoop** [comment]
com.alibaba.sdk.android.oss.ClientException: Expected a quoted string (position:DOCDECL @1:50 in java.io.InputStreamReader@442249a) 
org.xmlpull.v1.XmlPullParserException: Expected a quoted string (position:DOCDECL @1:50 in java.io.InputStreamReader@442249a) 
	at com.alibaba.sdk.android.oss.internal.ResponseParsers.parseResponseErrorXML(ResponseParsers.java:585)
	at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:212)
	at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:243)
	at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:243)
	at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:243)
	at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:243)
	at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:243)
	at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:44)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:784)
Caused by: org.xmlpull.v1.XmlPullParserException: Expected a quoted string (position:DOCDECL @1:50 in java.io.InputStreamReader@442249a) 
	at org.kxml2.io.KXmlParser.readQuotedId(KXmlParser.java:671)
	at org.kxml2.io.KXmlParser.readExternalId(KXmlParser.java:650)
	at org.kxml2.io.KXmlParser.readDoctype(KXmlParser.java:591)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:421)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
	at com.alibaba.sdk.android.oss.internal.ResponseParsers.parseResponseErrorXML(ResponseParsers.java:576)
	... 11 more

**Comment by andoop** [comment]
api 'com.aliyun.dpa:oss-android-sdk:2.8.3'

**Comment by 1019272778** [comment]
oss 后端返回的信息都是xml格式的，这样的错误可能是网络请求还没到oss server，直接在网络层就出错。返回的非xml格式的错误。
是否可以抓包，看看具体的错误信息是什么呢？
