### ISSUE TITLE
最新版初始化OssClient时报线程错误

### ISSUE THREAD

**Issue by BlainPeng** [aliyun/aliyun-oss-android-sdk#155]
`android.os.NetworkOnMainThreadException
01-02 13:41:38.524 32380-32380/W/System.err:     at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1288)
01-02 13:41:38.524 32380-32380/W/System.err:     at java.net.InetAddress.lookupHostByName(InetAddress.java:432)
01-02 13:41:38.524 32380-32380/W/System.err:     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:253)
01-02 13:41:38.524 32380-32380/W/System.err:     at java.net.InetAddress.getByName(InetAddress.java:306)
01-02 13:41:38.524 32380-32380/W/System.err:     at com.alibaba.sdk.android.oss.common.utils.OSSUtils.isValidateIP(OSSUtils.java:781)
01-02 13:41:38.524 32380-32380/W/System.err:     at com.alibaba.sdk.android.oss.OSSImpl.<init>(OSSImpl.java:117)
01-02 13:41:38.524 32380-32380/W/System.err:     at com.alibaba.sdk.android.oss.OSSClient.<init>(OSSClient.java:100)
01-02 13:41:38.525 32380-32380/W/System.err:     at com.alibaba.sdk.android.oss.OSSClient.<init>(OSSClient.java:88)`

**Comment by 1019272778** [comment]
在OSSClient创建时需要检查当前endpoint中是否包含ip格式。所以在UI主线程中创建ossclient会有类似的问题

**Comment by ypf168326** [comment]
如何解决呢？

**Comment by Jack-Xiao** [comment]
1. 这个报错是否会影响初始化？
2. 这个报错要如何解决呢？

**Comment by JesseWo** [comment]
同上

**Comment by ucssi-dongxd** [comment]
> * 这个报错是否会影响初始化？
> * 这个报错要如何解决呢？

严苛模式。不用管
