### ISSUE TITLE
com.alibaba.sdk.android.oss.ClientException: [ErrorMessage]: Unexpected exception!Failed resolution of: Lorg/apache/commons/codec/binary/Base64;

### ISSUE THREAD

**Issue by addhaloka** [aliyun/aliyun-oss-android-sdk#165]
com.alibaba.sdk.android.oss.ClientException: [ErrorMessage]: Unexpected exception!Failed resolution of: Lorg/apache/commons/codec/binary/Base64;
        at com.alibaba.sdk.android.oss.internal.OSSAsyncTask.getResult(OSSAsyncTask.java:69)
        at com.alibaba.sdk.android.oss.internal.InternalRequestOperation.syncPutObject(InternalRequestOperation.java:193)
        at com.alibaba.sdk.android.oss.OSSImpl.putObject(OSSImpl.java:182)
        at com.alibaba.sdk.android.oss.OSSClient.putObject(OSSClient.java:164)

**Comment by smxy34** [comment]
请问这个问题是怎么处理的呢
