### ISSUE TITLE
ObjectURLPresigner中url签名报错

### ISSUE THREAD

**Issue by aliyoge** [aliyun/aliyun-oss-android-sdk#172]
![Screen Shot 2019-04-22 at 5 00 23 PM](https://user-images.githubusercontent.com/12035097/56493077-718dfb80-6520-11e9-8f05-b9a39864ccd1.png)

```
2019-04-22 17:02:51.033 4646-4752/? E/AndroidRuntime: FATAL EXCEPTION: Thread-7
    Process: com.xxxxx.xxxx_mobile, PID: 4646
    java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at com.alibaba.sdk.android.oss.internal.ObjectURLPresigner.presignConstrainedURL(ObjectURLPresigner.java:101)
        at com.alibaba.sdk.android.oss.internal.ObjectURLPresigner.presignConstrainedURL(ObjectURLPresigner.java:126)
        at com.alibaba.sdk.android.oss.OSSImpl.presignConstrainedObjectURL(OSSImpl.java:458)
        at com.alibaba.sdk.android.oss.OSSClient.presignConstrainedObjectURL(OSSClient.java:418)
        at com.jlcool.aliossflutter.AliossflutterPlugin$11.run(AliossflutterPlugin.java:532)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by aliyoge** [comment]
```
String url = oss.presignConstrainedObjectURL("<bucketName>", "<objectKey>", 30 * 60);
```

同样的参数，`bucketName`、`objectKey`，iOS的SDK能正确的算出签名，并返回可用url。
