### ISSUE TITLE
报错read failed: EBADF (Bad file number)

### ISSUE THREAD

**Issue by devzld** [aliyun/aliyun-oss-android-sdk#181]
com.alibaba.sdk.android.oss.ClientException: read failed: EBADF (Bad file number)
07-10 14:57:24.320 3609-4566 W: [ErrorMessage]: read failed: EBADF (Bad file number)
07-10 14:57:24.320 3609-4566 W:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:200)
07-10 14:57:24.320 3609-4566 W:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:239)
07-10 14:57:24.321 3609-4566 W:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:239)
07-10 14:57:24.321 3609-4566 W:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:44)
07-10 14:57:24.321 3609-4566 W:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-10 14:57:24.321 3609-4566 W:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-10 14:57:24.321 3609-4566 W:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-10 14:57:24.321 3609-4566 W:     at java.lang.Thread.run(Thread.java:818)
07-10 14:57:24.321 3609-4566 W: Caused by: java.io.IOException: read failed: EBADF (Bad file number)
07-10 14:57:24.322 3609-4566 W:     at libcore.io.IoBridge.read(IoBridge.java:482)
07-10 14:57:24.322 3609-4566 W:     at java.io.FileInputStream.read(FileInputStream.java:177)
07-10 14:57:24.322 3609-4566 W:     at okio.InputStreamSource.read(Okio.kt:102)
07-10 14:57:24.322 3609-4566 W:     at com.alibaba.sdk.android.oss.network.ProgressTouchableRequestBody.writeTo(ProgressTouchableRequestBody.java:56)
07-10 14:57:24.322 3609-4566 W:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
07-10 14:57:24.322 3609-4566 W:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
07-10 14:57:24.322 3609-4566 W:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
07-10 14:57:24.322 3609-4566 W:     at com.android.tools.profiler.agent.okhttp.OkHttp3Interceptor.intercept(OkHttp3Interceptor.java:57)
07-10 14:57:24.322 3609-4566 W:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
07-10 14:57:24.322 3609-4566 W:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
07-10 14:57:24.323 3609-4566 W:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
07-10 14:57:24.323 3609-4566 W:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
07-10 14:57:24.323 3609-4566 W:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
07-10 14:57:24.323 3609-4566 W:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
07-10 14:57:24.323 3609-4566 W:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
07-10 14:57:24.323 3609-4566 W:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
07-10 14:57:24.323 3609-4566 W:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
07-10 14:57:24.323 3609-4566 W:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
07-10 14:57:24.323 3609-4566 W:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
07-10 14:57:24.323 3609-4566 W:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
07-10 14:57:24.323 3609-4566 W:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
07-10 14:57:24.323 3609-4566 W:     at okhttp3.RealCall.execute(RealCall.java:77)
07-10 14:57:24.323 3609-4566 W:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:177)
07-10 14:57:24.323 3609-4566 W: 	... 7 more
07-10 14:57:24.324 3609-4566 W: Caused by: android.system.ErrnoException: read failed: EBADF (Bad file number)
07-10 14:57:24.325 3609-4566 W:     at libcore.io.Posix.readBytes(Native Method)
07-10 14:57:24.325 3609-4566 W:     at libcore.io.Posix.read(Posix.java:165)
07-10 14:57:24.325 3609-4566 W:     at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
07-10 14:57:24.325 3609-4566 W:     at libcore.io.IoBridge.read(IoBridge.java:472)

**Comment by pushuhengyang** [comment]
可否把相关代码贴出来

**Comment by FWJerome** [comment]
我也遇到了，请问楼主解决没有？MIUI10.2和VIVO X7出现这个问题，华为mgic2没有问题。
<img width="869" alt="WX20191008-190156@2x" src="https://user-images.githubusercontent.com/12042541/66390916-4b8ce280-e9fe-11e9-94f4-525a884ed8a0.png">
<img width="1019" alt="WX20191008-190227@2x" src="https://user-images.githubusercontent.com/12042541/66390925-50519680-e9fe-11e9-9178-039d9d4846f6.png">

**Comment by pushuhengyang** [comment]
这个问题还没有遇到过 可以试试https://stackoverflow.com/questions/14584755/read-failed-ebadf-bad-file-number

**Comment by FWJerome** [comment]
我权限这些都给了。动态权限也获取得到了。真的很怪。。部分手机就报这个错

**Comment by yyyAndroid** [comment]
遇到了，同问

**Comment by liulei9385** [comment]
请查看一下这篇文章，应该能解决的
https://www.jianshu.com/p/3608630af86a

**Comment by EmMper** [comment]
同样遇到这个问题了。去年的issue怎么到现在也没有人维护呢
