### ISSUE TITLE
java.lang.Throwable: Explicit termination method 'close' not called

### ISSUE THREAD

**Issue by meifangshala** [aliyun/aliyun-oss-android-sdk#193]
java.lang.Throwable: Explicit termination method 'close' not called

at dalvik.system.CloseGuard.open(CloseGuard.java:223)

at java.io.FileInputStream.<init>(FileInputStream.java:156)

at com.android.okhttp.okio.Okio.source(Okio.java:164)

at com.android.okhttp.internal.io.FileSystem$1.source(FileSystem.java:44)

at com.android.okhttp.internal.DiskLruCache$Entry.snapshot(DiskLruCache.java:1028)

at com.android.okhttp.internal.DiskLruCache.get(DiskLruCache.java:429)

at com.android.okhttp.Cache.get(Cache.java:184)

at com.android.okhttp.Cache$1.get(Cache.java:139)

at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:210)

at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)

at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)

at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)

at com.alibaba.sdk.android.oss.common.utils.HttpdnsMini$QueryHostTask.call(SourceFile:138)

at com.alibaba.sdk.android.oss.common.utils.HttpdnsMini$QueryHostTask.call(SourceFile:120)

at java.util.concurrent.FutureTask.run(FutureTask.java:266)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)

at java.lang.Thread.run(Thread.java:764)

**Comment by pushuhengyang** [comment]
> java.lang.Throwable: Explicit termination method 'close' not called
> 
> at dalvik.system.CloseGuard.open(CloseGuard.java:223)
> 
> at java.io.FileInputStream.(FileInputStream.java:156)
> 
> at com.android.okhttp.okio.Okio.source(Okio.java:164)
> 
> at com.android.okhttp.internal.io.FileSystem$1.source(FileSystem.java:44)
> 
> at com.android.okhttp.internal.DiskLruCache$Entry.snapshot(DiskLruCache.java:1028)
> 
> at com.android.okhttp.internal.DiskLruCache.get(DiskLruCache.java:429)
> 
> at com.android.okhttp.Cache.get(Cache.java:184)
> 
> at com.android.okhttp.Cache$1.get(Cache.java:139)
> 
> at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:210)
> 
> at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
> 
> at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
> 
> at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
> 
> at com.alibaba.sdk.android.oss.common.utils.HttpdnsMini$QueryHostTask.call(SourceFile:138)
> 
> at com.alibaba.sdk.android.oss.common.utils.HttpdnsMini$QueryHostTask.call(SourceFile:120)
> 
> at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
> 
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
> 
> at java.lang.Thread.run(Thread.java:764)

可以运行吗 应该是流没有关闭
