### ISSUE TITLE
Caused by: android.system.ErrnoException: statvfs failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by hexi** [aliyun/aliyun-oss-android-sdk#208]
# 崩溃线程: oss-android-log-thread
```
Caused by: android.system.ErrnoException: statvfs failed: ENOENT (No such file or directory)
at libcore.io.Posix.statvfs(Native Method)
at libcore.io.BlockGuardOs.statvfs(BlockGuardOs.java:298)
at android.system.Os.statvfs(Os.java:459)
at android.os.StatFs.doStat(StatFs.java:44)
at android.os.StatFs.<init>(StatFs.java:39)
at com.alibaba.sdk.android.oss.common.OSSLogToFileUtils.readSDCardSpace(OSSLogToFileUtils.java:4)
at com.alibaba.sdk.android.oss.common.OSSLogToFileUtils.getLogFile(OSSLogToFileUtils.java:2)
at com.alibaba.sdk.android.oss.common.OSSLogToFileUtils.access$200(OSSLogToFileUtils.java:1)
at com.alibaba.sdk.android.oss.common.OSSLogToFileUtils$1.run(OSSLogToFileUtils.java:1)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1115)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:590)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by pushuhengyang** [comment]
这个是  读SD卡空间的方法 报错，请问android那个版本，SDK 哪个版本，是否开通读写权限

**Comment by fanjianhai** [comment]
![image](https://user-images.githubusercontent.com/13557071/77395759-402b4900-6ddd-11ea-860f-22e8e8abe98b.png)
这是我的bugly奔溃日志信息

**Comment by mutour** [comment]
如果没有开启enableLog可以不要做这个事情吗？我也遇到这个问题，直接报，而且还是部分手机会
```
java.lang.IllegalArgumentException: Invalid path: /storage/emulated/0
    at android.os.StatFs.doStat(StatFs.java:51)
    at android.os.StatFs.(StatFs.java:41)
    at com.alibaba.sdk.android.oss.common.OSSLogToFileUtils.readSDCardSpace(:128)
    at com.alibaba.sdk.android.oss.common.OSSLogToFileUtils.getLogFile(:199)
    at com.alibaba.sdk.android.oss.common.OSSLogToFileUtils.access$200(:20)
```

**Comment by Flings** [comment]
我们这边也遇到同样的问题，望官方能够跟进，修复这个问题

附上stackoverflow上的一个帖子

https://stackoverflow.com/questions/47238691/android-system-errnoexception-error

**Comment by Flings** [comment]
补充上一条，我们这边报错机型包括： 5.0，5.1，9.0，10.0  且5.1占比80%
