### ISSUE TITLE
oss上传文件失败

### ISSUE THREAD

**Issue by wy799172467** [aliyun/aliyun-oss-android-sdk#210]
`com.alibaba.sdk.android.oss.ClientException: Expected a quoted string (position:DOCDECL @1:50 in java.io.InputStreamReader@99aba86)
org.xmlpull.v1.XmlPullParserException: Expected a quoted string (position:DOCDECL @1:50 in java.io.InputStreamReader@99aba86)
at com.alibaba.sdk.android.oss.internal.ResponseParsers.parseResponseErrorXML(ResponseParsers.java:585)
at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:212)
at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:44)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
Caused by: org.xmlpull.v1.XmlPullParserException: Expected a quoted string (position:DOCDECL @1:50 in java.io.InputStreamReader@99aba86)
at org.kxml2.io.KXmlParser.readQuotedId(KXmlParser.java:671)
at org.kxml2.io.KXmlParser.readExternalId(KXmlParser.java:650)
at org.kxml2.io.KXmlParser.readDoctype(KXmlParser.java:591)
at org.kxml2.io.KXmlParser.next(KXmlParser.java:421)
at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
at com.alibaba.sdk.android.oss.internal.ResponseParsers.parseResponseErrorXML(ResponseParsers.java:576)
... 6 more

**Comment by pushuhengyang** [comment]
@wy799172467 网络是否可以正常访问，可否提供完整日志，这个问题一般是网络不正常

**Comment by wy799172467** [comment]
附件是oss上传日志












在 2020-03-02 18:28:11，"朴树" <notifications@github.com> 写道：

@wy799172467 网络是否可以正常访问，可否提供完整日志，这个问题一般是网络不正常

**Comment by pushuhengyang** [comment]
@wy799172467  并没有附件

**Comment by southbaird** [comment]
更新最新版本
