### ISSUE TITLE
【2.9.3】NetworkOnMainThreadException

### ISSUE THREAD

**Issue by JingweiWang** [aliyun/aliyun-oss-android-sdk#214]
android.os.NetworkOnMainThreadException
    at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1571)
    at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
    at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
    at java.net.InetAddress.getByName(InetAddress.java:1106)
    at com.alibaba.sdk.android.oss.common.utils.OSSUtils.isValidateIP(OSSUtils.java:795)
    at com.alibaba.sdk.android.oss.OSSImpl.<init>(OSSImpl.java:133)
    at com.alibaba.sdk.android.oss.OSSClient.<init>(OSSClient.java:116)
    at com.alibaba.sdk.android.oss.OSSClient.<init>(OSSClient.java:104)

**Comment by wushuai1415** [comment]
OSS初始化是会调用InetAddress.getByName检查endpoint的host是否为ip，访问DNS服务器慢时会卡住主线程
