### ISSUE TITLE
NetworkOnMainThreadException

### ISSUE THREAD

**Issue by ztz736665550** [aliyun/aliyun-oss-android-sdk#220]
android.os.NetworkOnMainThreadException
2020-05-25 12:16:26.098 18711-18711/com.jingyinglutong.pda W/System.err:     at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1303)
2020-05-25 12:16:26.098 18711-18711/com.jingyinglutong.pda W/System.err:     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:86)
2020-05-25 12:16:26.098 18711-18711/com.jingyinglutong.pda W/System.err:     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
2020-05-25 12:16:26.098 18711-18711/com.jingyinglutong.pda W/System.err:     at java.net.InetAddress.getByName(InetAddress.java:708)
2020-05-25 12:16:26.098 18711-18711/com.jingyinglutong.pda W/System.err:     at com.alibaba.sdk.android.oss.common.utils.OSSUtils.isValidateIP(OSSUtils.java:795)
2020-05-25 12:16:26.098 18711-18711/com.jingyinglutong.pda W/System.err:     at com.alibaba.sdk.android.oss.OSSImpl.<init>(OSSImpl.java:133)
2020-05-25 12:16:26.098 18711-18711/com.jingyinglutong.pda W/System.err:     at com.alibaba.sdk.android.oss.OSSClient.<init>(OSSClient.java:116)

**Comment by wushuai1415** [comment]
OSS初始化是会调用InetAddress.getByName检查endpoint的host是否为ip，访问DNS服务器慢时会卡住主线程

**Comment by shaobin0604** [comment]
> OSS初始化是会调用InetAddress.getByName检查endpoint的host是否为ip，访问DNS服务器慢时会卡住主线程

有发布新版本解决这个问题么？
