### ISSUE TITLE
 java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/conn/ssl/DefaultHostnameVerifier;

### ISSUE THREAD

**Issue by StevenYan88** [aliyun/aliyun-oss-android-sdk#227]
at com.aliyun.oss.common.comm.DefaultServiceClient.createHttpClientConnectionManager(DefaultServiceClient.java:274)
        at com.aliyun.oss.common.comm.DefaultServiceClient.<init>(DefaultServiceClient.java:90)
        at com.aliyun.oss.OSSClient.<init>(OSSClient.java:223)

**Comment by wushuai1415** [comment]
你这是哪个版本啊
