### ISSUE TITLE
om.alibaba.sdk.android.oss.ClientException: Stream Closed

### ISSUE THREAD

**Issue by StevenYan88** [aliyun/aliyun-oss-android-sdk#248]
2020-11-03 14:40:04.979 9094-9303/com.flyingwings.cleanrobot W/System.err: com.alibaba.sdk.android.oss.ClientException: Stream Closed
2020-11-03 14:40:04.980 9094-9303/com.flyingwings.cleanrobot W/System.err: [ErrorMessage]: Stream Closed
2020-11-03 14:40:04.980 9094-9303/com.flyingwings.cleanrobot W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:200)
2020-11-03 14:40:04.980 9094-9303/com.flyingwings.cleanrobot W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:239)
2020-11-03 14:40:04.980 9094-9303/com.flyingwings.cleanrobot W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:239)
2020-11-03 14:40:04.980 9094-9303/com.flyingwings.cleanrobot W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:44)
2020-11-03 14:40:04.980 9094-9303/com.flyingwings.cleanrobot W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
2020-11-03 14:40:04.980 9094-9303/com.flyingwings.cleanrobot W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2020-11-03 14:40:04.980 9094-9303/com.flyingwings.cleanrobot W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2020-11-03 14:40:04.980 9094-9303/com.flyingwings.cleanrobot W/System.err:     at java.lang.Thread.run(Thread.java:761)
2020-11-03 14:40:04.981 9094-9303/com.flyingwings.cleanrobot W/System.err: Caused by: java.io.IOException: Stream Closed
2020-11-03 14:40:04.981 9094-9303/com.flyingwings.cleanrobot W/System.err:     at java.io.FileInputStream.read(FileInputStream.java:246)
2020-11-03 14:40:04.981 9094-9303/com.flyingwings.cleanrobot W/System.err:     at okio.Okio$2.read(Okio.java:140)
2020-11-03 14:40:04.981 9094-9303/com.flyingwings.cleanrobot W/System.err:     at com.alibaba.sdk.android.oss.network.ProgressTouchableRequestBody.writeTo(ProgressTouchableRequestBody.java:56)
2020-11-03 14:40:04.981 9094-9303/com.flyingwings.cleanrobot W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:69)
2020-11-03 14:40:04.981 9094-9303/com.flyingwings.cleanrobot W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2020-11-03 14:40:04.981 9094-9303/com.flyingwings.cleanrobot W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
2020-11-03 14:40:04.981 9094-9303/com.flyingwings.cleanrobot W/System.err:     at com.android.tools.profiler.agent.okhttp.OkHttp3Interceptor.intercept(OkHttp3Interceptor.java:57)
2020-11-03 14:40:04.981 9094-9303/com.flyingwings.cleanrobot W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2020-11-03 14:40:04.981 9094-9303/com.flyingwings.cleanrobot W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
2020-11-03 14:40:04.981 9094-9303/com.flyingwings.cleanrobot W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2020-11-03 14:40:04.982 9094-9303/com.flyingwings.cleanrobot W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
2020-11-03 14:40:04.982 9094-9303/com.flyingwings.cleanrobot W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
2020-11-03 14:40:04.982 9094-9303/com.flyingwings.cleanrobot W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2020-11-03 14:40:04.982 9094-9303/com.flyingwings.cleanrobot W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
2020-11-03 14:40:04.982 9094-9303/com.flyingwings.cleanrobot W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
2020-11-03 14:40:04.982 9094-9303/com.flyingwings.cleanrobot W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2020-11-03 14:40:04.982 9094-9303/com.flyingwings.cleanrobot W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
2020-11-03 14:40:04.982 9094-9303/com.flyingwings.cleanrobot W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2020-11-03 14:40:04.982 9094-9303/com.flyingwings.cleanrobot W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
2020-11-03 14:40:04.982 9094-9303/com.flyingwings.cleanrobot W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
2020-11-03 14:40:04.982 9094-9303/com.flyingwings.cleanrobot W/System.err:     at okhttp3.RealCall.execute(RealCall.java:81)
2020-11-03 14:40:04.982 9094-9303/com.flyingwings.cleanrobot W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:177)
2020-11-03 14:40:04.982 9094-9303/com.flyingwings.cleanrobot W/System.err: 	... 7 more

**Comment by wushuai1415** [comment]
https://www.jianshu.com/p/3608630af86a?utm_campaign=maleskine&utm_content=note&utm_medium=seo_notes&utm_source=recommendation

**Comment by liuqqi** [comment]
> https://www.jianshu.com/p/3608630af86a?utm_campaign=maleskine&utm_content=note&utm_medium=seo_notes&utm_source=recommendation

我的androidstudio没有那个开关，也出现stream closed问题。改怎么解决
