### ISSUE TITLE
Failed to resolve: oss-android-sdk-2.9.5???

### ISSUE THREAD

**Issue by Quy520** [aliyun/aliyun-oss-android-sdk#250]

**Comment by wushuai1415** [comment]
看一下依赖怎么写的

**Comment by Quy520** [comment]
> 看一下依赖怎么写的
com.aliyun.dpa:oss-android-sdk:+

**Comment by wushuai1415** [comment]
@Quy520 清一下gradle缓存

**Comment by Quy520** [comment]
> @Quy520 清一下gradle缓存

不行，我已经Rebuild 和 Invalidate Caches/Restart  还是不行

**Comment by wushuai1415** [comment]
@Quy520 试试gradlew build --refresh-dependencies

**Comment by zplblue** [comment]
2.9.5 我这里也出现了问题。使用Flutter 插件。依赖默认使用：+；
出现：
`flutter: [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/OkHttpClient$Builder;
        at com.alibaba.sdk.android.oss.internal.InternalRequestOperation.<init>(InternalRequestOperation.java:78)
        at com.alibaba.sdk.android.oss.OSSImpl.<init>(OSSImpl.java:145)
        at com.alibaba.sdk.android.oss.OSSClient.<init>(OSSClient.java:116)`

一开始以为是混淆之类的问题。最后手动指定版本2.9.4。就不会报错了。

**Comment by wushuai1415** [comment]
@zplblue 看一下2.9.5的pom

**Comment by Quy520** [comment]
> @Quy520 试试gradlew build --refresh-dependencies
什么意思？怎么操作？

**Comment by wushuai1415** [comment]
@Quy520 命令 刷新一下依赖

**Comment by Quy520** [comment]
> @Quy520 命令 刷新一下依赖

还是不行

**Comment by wushuai1415** [comment]
@Quy520 指定2.9.4可以么

**Comment by aleron08** [comment]
> @Quy520 指定2.9.4可以么

同样的问题，手动指定2.9.4就好了

**Comment by Quy520** [comment]
> @Quy520 指定2.9.4可以么

可以是可以了，但是我项目里面有阿里的视屏编辑的lib 里面也有这个依赖，我改成了2.9.4之后重新clear一下 还是包这个错误

**Comment by wushuai1415** [comment]
@Quy520 仓库是用的jcenter吧？

**Comment by Quy520** [comment]
> @Quy520 仓库是用的jcenter吧？

是的

**Comment by wushuai1415** [comment]
@Quy520 gradle什么版本

**Comment by Quy520** [comment]
> @Quy520 gradle什么版本

6.1.1

**Comment by wushuai1415** [comment]
@Quy520 在尝试把gradle缓存目录里的库删掉，重新拉试试

**Comment by Quy520** [comment]
> gradle缓存目录里的库

一样，都不行，一直报这个错

**Comment by Quy520** [comment]
> @Quy520 在尝试把gradle缓存目录里的库删掉，重新拉试试

* What went wrong:
Execution failed for task ':AliyunEditor:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':AliyunEditor:debugCompileClasspath'.
   > Could not find oss-android-sdk-2.9.5.jar (com.aliyun.dpa:oss-android-sdk:2.9.5).
     Searched in the following locations:
         https://jcenter.bintray.com/com/aliyun/dpa/oss-android-sdk/2.9.5/oss-android-sdk-2.9.5.jar

**Comment by wushuai1415** [comment]
@Quy520 gradlew build --refresh-dependencies再试一次

**Comment by Quy520** [comment]
> @Quy520 gradlew build --refresh-dependencies再试一次

FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 587ms
报错，还有其他方法不？之前一直好好地

**Comment by wushuai1415** [comment]
@Quy520 改一下sdk的版本，在试一下。我这边没法复现你这个问题，我也在想办法，这个应该是之前上传2.9.5失败后本地缓存导致的

**Comment by Quy520** [comment]
> @Quy520 改一下sdk的版本，在试一下。我这边没法复现你这个问题，我也在想办法，这个应该是之前上传2.9.5失败后本地缓存导致的

那清除本地缓存还有其他方法不？那个一直失败

**Comment by wushuai1415** [comment]
@Quy520 现在拉2.9.5报的是什么错

**Comment by Quy520** [comment]
> @Quy520 现在拉2.9.5报的是什么错

Failed to resolve: oss-android-sdk-2.9.5

**Comment by Quy520** [comment]
> > @Quy520 现在拉2.9.5报的是什么错
> 
> Failed to resolve: oss-android-sdk-2.9.5

这个问题什么时候可以解决啊，不然我开不来这个项目了哈哈。。。

**Comment by wushuai1415** [comment]
@Quy520 方便加个钉钉沟通吗

**Comment by Quy520** [comment]
> @Quy520 方便加个钉钉沟通吗

好的，17621678780

**Comment by Quy520** [comment]
> > @Quy520 方便加个钉钉沟通吗
> 
> 好的，17621678780

钉钉号：qianshide   应该俩个都能搜索到



>

**Comment by LuoboDcom** [comment]
https://jcenter.bintray.com/com/aliyun/dpa/oss-android-sdk/2.9.5/oss-android-sdk-2.9.5.jar

**Comment by wushuai1415** [comment]
@LuoboDcom 清一下gradle缓存

**Comment by LuoboDcom** [comment]
> @LuoboDcom 清一下gradle缓存

不行了，试了几次，我现在直接依赖jar包了

**Comment by StandOpen** [comment]
有人解决了吗，我的项目只是用了com.aliyun.video.android:upload库，也是突然报这个错误

**Comment by LuoboDcom** [comment]
> 有人解决了吗，我的项目只是用了com.aliyun.video.android:upload库，也是突然报这个错误

直接使用 jar包呀

**Comment by wushuai1415** [comment]
清下.gradle/caches/modules-2下的缓存

**Comment by StandOpen** [comment]
> 清下.gradle/caches/modules-2下的缓存

不好使，还是直接用jar包吧

**Comment by StandOpen** [comment]
等到2.9.5的tag是不是就会好了？

**Comment by wushuai1415** [comment]
@StandOpen 和tag没关系，之前上传失败导致的问题，解决了几个了都是缓存的问题

**Comment by shingohu** [comment]
就不能上传个新的2.9.6吗 怎么清理都没用,直接导致app闪退
flutter: [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/OkHttpClient$Builder; at com.alibaba.sdk.android.oss.internal.InternalRequestOperation.<init>(InternalRequestOperation.java:78) at com.alibaba.sdk.android.oss.OSSImpl.<init>(OSSImpl.java:145) at com.alibaba.sdk.android.oss.OSSClient.<init>(OSSClient.java:116)

**Comment by wushuai1415** [comment]
> 就不能上传个新的2.9.6吗 怎么清理都没用,直接导致app闪退
> flutter: [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/OkHttpClient$Builder; at com.alibaba.sdk.android.oss.internal.InternalRequestOperation.(InternalRequestOperation.java:78) at com.alibaba.sdk.android.oss.OSSImpl.(OSSImpl.java:145) at com.alibaba.sdk.android.oss.OSSClient.(OSSClient.java:116)

你再依赖一下okHttp OSS依赖的版本：'com.squareup.okhttp3:okhttp:3.4.1' 'com.squareup.okio:okio:1.14.0'
