### ISSUE TITLE
Android6.0   6.0.1线上包上传失败

### ISSUE THREAD

**Issue by YuToo** [aliyun/aliyun-oss-android-sdk#251]
oss版本：2.9.5
手机型号：红米4 6.0.1/  红米4A 6.0.1/ vivo Y66 6.0.1/ oppo a57 6.0.1/ 华为p8 6.0 
系统版本：6.0.1/6.0
问题描述：debug包运行正常，release包混淆之后运行报错，错误信息如下，混淆配置已确认按照文档加入，其他系统版本暂未发现异常，
异常信息：
com.alibaba.sdk.android.oss.ClientException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
[ErrorMessage]: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:71)
at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:90)
at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:90)
at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:1)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:328)
at j.a.b.f.a(RealConnection.java:94)
at j.a.b.f.a(RealConnection.java:73)
at j.a.b.f.a(RealConnection.java:15)
at j.a.b.e.a(ExchangeFinder.java:51)
at j.a.b.e.a(ExchangeFinder.java:12)
at j.a.b.e.a(ExchangeFinder.java:6)
at j.a.b.k.a(Transmitter.java:23)
at j.a.b.b.intercept(ConnectInterceptor.java:5)
at j.a.c.h.a(RealInterceptorChain.java:11)
at j.a.c.h.a(RealInterceptorChain.java:2)
at j.a.a.b.intercept(CacheInterceptor.java:22)
at j.a.c.h.a(RealInterceptorChain.java:11)
at j.a.c.h.a(RealInterceptorChain.java:2)
at j.a.c.a.intercept(BridgeInterceptor.java:22)
at j.a.c.h.a(RealInterceptorChain.java:11)
at j.a.c.k.intercept(RetryAndFollowUpInterceptor.java:6)
at j.a.c.h.a(RealInterceptorChain.java:11)
at j.a.c.h.a(RealInterceptorChain.java:2)
at j.H.a(RealCall.java:16)
at j.H.execute(RealCall.java:8)
at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:57)
... 7 more
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:324)
at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:225)
at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:115)
at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:556)
at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
... 28 more
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
... 34 more

**Comment by YuToo** [comment]
继续测试发现与混淆无关，debug混淆了也没问题，release不混淆也会报错

**Comment by wushuai1415** [comment]
@YuToo 这两个系统百分百会报错么

**Comment by YuToo** [comment]
我这边测试百分百报错

**Comment by wushuai1415** [comment]
@YuToo 你的endpoint是什么，切换到2.9.4正常么

**Comment by YuToo** [comment]
> @YuToo 你的endpoint是什么，切换到2.9.4正常么

endpoint是自己的域名，没测2.9.4，最后对比了下线上和线下就是endpoint协议导致的，线上用的https，换成http就正常了，但是https在其他的版本7.0，10.0测试都没问题，就6.0/6.0.1有问题

**Comment by wushuai1415** [comment]
@YuToo 试一下OSS的默认endpoint会不会出错

**Comment by YuToo** [comment]
> @YuToo 试一下OSS的默认endpoint会不会出错

试了默认的endpoint没问题，那这种情况是我的域名的ssl证书有问题么？但是为什么不是所有机型都有问题呢？我自己APP的接口请求也是https在6.0也能正常请求。

**Comment by wushuai1415** [comment]
证书的验证是由okhttp做的，正常来说不应该出现这种情况，OSS的证书没问题这边也无法debug

**Comment by YuToo** [comment]
@wushuai1415 好的，谢谢，先换回http用了。
