### ISSUE TITLE
上传文件老是抛出转换异常是什么情况

### ISSUE THREAD

**Issue by LgSecret** [aliyun/aliyun-oss-android-sdk#264]
com.alibaba.sdk.android.oss.ClientException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject

**Comment by wushuai1415** [comment]
有完整的异常信息吗

**Comment by LgSecret** [comment]
org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
 W/System.err:     at com.alibaba.sdk.android.oss.common.auth.OSSAuthCredentialsProvider.getFederationToken(OSSAuthCredentialsProvider.java:73)
W/System.err:     at com.alibaba.sdk.android.oss.common.auth.OSSFederationCredentialProvider.getValidFederationToken(OSSFederationCredentialProvider.java:30)
 W/System.err:     at com.alibaba.sdk.android.oss.common.utils.OSSUtils.signRequest(OSSUtils.java:681)
2021-01-18 17:07:45.900 9291-11616/ W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:87)
2021-01-18 17:07:45.900 9291-11616/ W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:243)
2021-01-18 17:07:45.900 9291-11616/ W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:243)
2021-01-18 17:07:45.900 9291-11616/ W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:45)
2021-01-18 17:07:45.900 9291-11616/W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-01-18 17:07:45.900 9291-11616/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-01-18 17:07:45.900 9291-11616/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-01-18 17:07:45.900 9291-11616/ W/System.err:     at java.lang.Thread.run(Thread.java:919)
2021-01-18 17:07:45.901 9291-11616/ W/System.err: Caused by: org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
2021-01-18 17:07:45.901 9291-11616/ W/System.err:     at org.json.JSON.typeMismatch(JSON.java:112)
2021-01-18 17:07:45.901 9291-11616/ W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:168)
2021-01-18 17:07:45.901 9291-11616/ W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:181)
2021-01-18 17:07:45.901 9291-11616/ W/System.err:     at com.alibaba.sdk.android.oss.common.auth.OSSAuthCredentialsProvider.getFederationToken(OSSAuthCredentialsProvider.java:58)

**Comment by wushuai1415** [comment]
getFederationToken方法是从您的server获取token，异常应该是您的server返回的数据无法解析

**Comment by LgSecret** [comment]
请求服务端获取返回值如下{"StatusCode":"200","AccessKeyId":"STS.NU392MDn75WgbSQHR85jfRYvB","AccessKeySecret":"9aVPmcUgXRUBspFjnZJ3gaUVdhcbUMBcZ5RAefMwWZeP","SecurityToken":"CAISgwJ1q6Ft5B2yfSjIr5aGcoj5qbEWgpWMYHXgrFJtOeVKvZzdoDz2IH1NfXhrA+8bvvkynW1T5/gclqB6T55OSAmcNZIoOWK5O5rnMeT7oMWQweEuqv/MQBq+aXPS2MvVfJ+KLrf0ceusbFbpjzJ6xaCAGxypQ12iN+/i6/clFKN1ODO1dj1bHtxbCxJ/ocsBTxvrOO2qLwThjxi7biMqmHIl1Dwgsvngn5zFsUqC1gWn8IJP+dSteKrDRtJ3IZJyX+2y2OFLbafb2EZSkUMXrf4n1/YbpGea44jAWAgPvQ/1Ou7V48BpKxRieq85FqhLof7xj/RkvfbJkID62/OE+X6v6Kq1GoABsMw5H1WwiGE6buvELX727C8I3ltqFOXqiB/T6ZF6n3QjHDeGlKaKGS0f8zpK81XvM65LBxFET9IIKoRsm2Oudbvw6KXG/hcWyFW0bnOz1xc9TjkfweBZB0BtX5tiZxdk3bOUkg3HFNdppTHG0Ud+UUjhvAKIP3QhZ+zMHL3UW1I=","Expiration":"2021-01-18T06:49:36Z"}
这个是阿里云返回的token

**Comment by wushuai1415** [comment]
这个异常是必现的吗

**Comment by LgSecret** [comment]
是的  去年的时候一直没问题，今年突然出现的

**Comment by wushuai1415** [comment]
我把返回的数据直接贴到代码里是没有问题的，你看下OSSAuthCredentialsProvider的getFederationToken里authData的值是什么

**Comment by LgSecret** [comment]
感谢大佬 ，是STS 地址的问题，把STS地址换成https就行了

**Comment by LgSecret** [comment]
com.alibaba.sdk.android.oss.ClientException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
 authData = IOUtils.readStreamAsString(input, OSSConstants.DEFAULT_CHARSET_NAME);
            if (mDecoder != null) {
                authData = mDecoder.decode(authData);
            }
            JSONObject jsonObj = new JSONObject(authData);
authData 转换异常 需要进行排查
