### ISSUE TITLE
 java.io.IOException: Stream Closed

### ISSUE THREAD

**Issue by 1145906886** [aliyun/aliyun-oss-android-sdk#267]
java.io.IOException: Stream Closed
     at java.io.FileInputStream.read(FileInputStream.java:306)
     at okio.InputStreamSource.read(JvmOkio.kt:90)
     at com.alibaba.sdk.android.oss.network.ProgressTouchableRequestBody.writeTo(ProgressTouchableRequestBody.java:56)
     at com.didichuxing.doraemonkit.util.DokitUtil.requestBodyToString(DokitUtil.java:48)
     at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.MockInterceptor.transformRequestBody(MockInterceptor.java:131)
     at com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.MockInterceptor.intercept(MockInterceptor.java:65)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
     at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
     at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:181)
     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:45)
     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
     at java.lang.Thread.run(Thread.java:919)

**Comment by wushuai1415** [comment]
debug看到 OSS读取完文件关闭了流后 com.didichuxing.doraemonkit.util.DokitUtil.requestBodyToString 又调用了一次writeTo读取导致异常

**Comment by cfJand** [comment]
我也遇到同样的问题，sdk啥时候更新修复下该问题呢？

**Comment by h3clikejava** [comment]
我也遇到同样的问题，sdk啥时候更新修复下该问题呢？搞了一下午，还以为是改错了哪里！

**Comment by huntersha** [comment]
https://blog.csdn.net/weixin_38620672/article/details/113886530
Android Studio中 Run --> EditConfigurations -->Profiling取消勾选即可
出现Stream closed的原因是打开了Android Profiler，额外添加了一个拦截器，这个拦截器关闭了Inputstream。


我的情况以前一直正常，突然就这样。 按上面文章关掉重启就可以了。 或者直接关掉IDE重启试试。

**Comment by 1145906886** [comment]
明天你好这是来自QQ邮箱的假期自动回复邮件。 
  
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
