### ISSUE TITLE
com.alibaba.sdk.android.oss.ClientException: Unexpected token (position:TEXT 400 Bad Request@1:16 in java.io.InputStreamReader@1722b0aa) 

### ISSUE THREAD

**Issue by Rongrkang** [aliyun/aliyun-oss-android-sdk#318]
2021-11-03 18:14:52.048 18882-20118/? W/System.err: com.alibaba.sdk.android.oss.ClientException: Unexpected token (position:TEXT 400 Bad Request@1:16 in java.io.InputStreamReader@1722b0aa) 
2021-11-03 18:14:52.048 18882-20118/? W/System.err: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT 400 Bad Request@1:16 in java.io.InputStreamReader@1722b0aa) 
2021-11-03 18:14:52.048 18882-20118/? W/System.err:     at com.alibaba.sdk.android.oss.internal.ResponseParsers.parseResponseErrorXML(ResponseParsers.java:850)
2021-11-03 18:14:52.048 18882-20118/? W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:218)
2021-11-03 18:14:52.048 18882-20118/? W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:47)
2021-11-03 18:14:52.048 18882-20118/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
2021-11-03 18:14:52.048 18882-20118/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
2021-11-03 18:14:52.048 18882-20118/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
2021-11-03 18:14:52.048 18882-20118/? W/System.err:     at java.lang.Thread.run(Thread.java:818)
2021-11-03 18:14:52.048 18882-20118/? W/System.err: Caused by: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT 400 Bad Request@1:16 in java.io.InputStreamReader@1722b0aa) 
2021-11-03 18:14:52.049 18882-20118/? W/System.err:     at org.kxml2.io.KXmlParser.next(KXmlParser.java:432)
2021-11-03 18:14:52.049 18882-20118/? W/System.err:     at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
2021-11-03 18:14:52.049 18882-20118/? W/System.err:     at com.alibaba.sdk.android.oss.internal.ResponseParsers.parseResponseErrorXML(ResponseParsers.java:841)
2021-11-03 18:14:52.049 18882-20118/? W/System.err: 	... 6 more

**Comment by wushuai1415** [comment]
开下日志看看

**Comment by Rongrkang** [comment]
> 开下日志看看


2021-11-04 10:48:19.119 7647-11650/? I/StorageManagerEx: path=/storage/emulated/0
2021-11-04 10:48:19.119 7647-11650/? I/StorageManagerEx: getDefaultPath path=/storage/emulated/0
2021-11-04 10:48:19.119 7647-11650/? D/OSS-Android-SDK: [Debug]: sd卡存储空间:1052860416kb
2021-11-04 10:48:19.119 7647-11650/? I/StorageManagerEx: path=/storage/emulated/0
2021-11-04 10:48:19.120 7647-11650/? I/StorageManagerEx: getDefaultPath path=/storage/emulated/0
2021-11-04 10:48:19.120 7647-11650/? I/OSS-Android-SDK: [INFO]: LogFilePath is: /storage/emulated/0/OSSLog/logs.csv
2021-11-04 10:48:19.163 7647-11651/? D/OSS-Android-SDK: [Debug]: [checkPartSize] - mFileLength : 8275
2021-11-04 10:48:19.165 7647-11651/? D/OSS-Android-SDK: [Debug]: [checkPartSize] - partSize : 262144
2021-11-04 10:48:19.168 7647-11651/? D/OSS-Android-SDK: [Debug]: [checkPartSize] - partNumber : 1
2021-11-04 10:48:19.168 7647-11651/? D/OSS-Android-SDK: [Debug]: [checkPartSize] - partSize : 8275
2021-11-04 10:48:19.168 7647-11651/? D/OSS-Android-SDK: [Debug]: [checkInitData] - partNumber : 1
2021-11-04 10:48:19.168 7647-11651/? D/OSS-Android-SDK: [Debug]: [checkInitData] - partSize : 8275
2021-11-04 10:48:19.178 7647-11651/? D/OSS-Android-SDK: [Debug]: user agent : (Linux/Android 5.1/HUAWEI%20TAG-AL00;HUAWEITAG-AL00)
2021-11-04 10:48:19.180 7647-11652/? I/OSS-Android-SDK: [INFO]: =====[device info]=====
    [INFO]: android_version：5.1
    [INFO]: mobile_model：HUAWEI TAG-AL00
2021-11-04 10:48:19.180 7647-11652/? D/OSS-Android-SDK: [Debug]: [call] - 
2021-11-04 10:48:19.188 7647-11652/? D/OSS-Android-SDK: [Debug]: signRequest start
2021-11-04 10:48:19.190 7647-11652/? D/OSS-Android-SDK: [Debug]: get contentToSign
2021-11-04 10:48:19.191 7647-11652/? D/OSS-Android-SDK: [Debug]: HmacSHA1
2021-11-04 10:48:19.191 7647-11652/? D/OSS-Android-SDK: [Debug]: 1
2021-11-04 10:48:19.191 7647-11652/? D/OSS-Android-SDK: [Debug]: sign start
2021-11-04 10:48:19.194 7647-11652/? D/OSS-Android-SDK: [Debug]: base64 start
2021-11-04 10:48:19.195 7647-11652/? D/OSS-Android-SDK: [Debug]: signed content: POST
    
    application/zip
    Thu, 04 Nov 2021 02:48:19 GMT
    x-oss-security-token:
    /wtswc-product-data/wc_data_zip/2021-11-04/zip/07d748b83a0b0729d9b5b9b36e3c9f6b.zip?uploads   
     ---------   signature: OSS LTAIJKWpRxag8lpb:WR8KOpXrrVp4r1jlQwiWJjf6GPw=
2021-11-04 10:48:19.195 7647-11652/? D/OSS-Android-SDK: [Debug]: get signature
2021-11-04 10:48:19.197 7647-11652/? D/OSS-Android-SDK: [Debug]:  scheme : http
2021-11-04 10:48:19.197 7647-11652/? D/OSS-Android-SDK: [Debug]:  originHost : oss-cn-hangzhou.aliyuncs.com
2021-11-04 10:48:19.197 7647-11652/? D/OSS-Android-SDK: [Debug]:  port : null
2021-11-04 10:48:19.198 7647-11652/? D/OSS-Android-SDK: [Debug]: [httpdnsmini] - refresh host: wtswc-product-data.oss-cn-hangzhou.aliyuncs.com
2021-11-04 10:48:19.204 7647-11653/? D/OSS-Android-SDK: [Debug]: [httpdnsmini] - buildUrl: https://203.107.1.1/181345/d?host=wtswc-product-data.oss-cn-hangzhou.aliyuncs.com
2021-11-04 10:48:19.204 7647-11653/? I/System.out: open:https://203.107.1.1/181345/d?host=wtswc-product-data.oss-cn-hangzhou.aliyuncs.com
2021-11-04 10:48:19.205 7647-11653/? D/libc-netbsd: [getaddrinfo]: mtk hostname=203.107.1.1; servname=(null); cache_mode=(null), netid=0; mark=0
2021-11-04 10:48:19.205 7647-11653/? D/libc-netbsd: getaddrinfo( app_uid:10106
2021-11-04 10:48:19.205 7647-11653/? D/libc-netbsd: getaddrinfo() uid prop:
2021-11-04 10:48:19.205 7647-11653/? D/libc-netbsd: getaddrinfo() getuid():10106
2021-11-04 10:48:19.205 7647-11653/? D/libc-netbsd: [getaddrinfo]: mtk ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
2021-11-04 10:48:19.208 7647-11653/? I/System.out: [CDS][DNS] getAllByNameImpl netId = 0
2021-11-04 10:48:19.208 7647-11653/? D/libc-netbsd: [getaddrinfo]: mtk hostname=203.107.1.1; servname=(null); cache_mode=(null), netid=0; mark=0
2021-11-04 10:48:19.209 7647-11653/? D/libc-netbsd: getaddrinfo( app_uid:10106
2021-11-04 10:48:19.209 7647-11653/? D/libc-netbsd: getaddrinfo() uid prop:
2021-11-04 10:48:19.209 7647-11653/? D/libc-netbsd: getaddrinfo() getuid():10106
2021-11-04 10:48:19.209 7647-11653/? D/libc-netbsd: [getaddrinfo]: mtk ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
2021-11-04 10:48:19.209 7647-11653/? I/System.out: [CDS]rx timeout:10000
2021-11-04 10:48:19.211 7647-11653/? I/System.out: [socket][4] connection /203.107.1.1:443;LocalPort=57919(10000)
2021-11-04 10:48:19.211 7647-11653/? I/System.out: [CDS]connect[/203.107.1.1:443] tm:10
2021-11-04 10:48:19.214 7647-11652/? D/OSS-Android-SDK: [Debug]: request---------------------
    request url=http://wtswc-product-data.oss-cn-hangzhou.aliyuncs.com/wc_data_zip/2021-11-04/zip/07d748b83a0b0729d9b5b9b36e3c9f6b.zip
    request params=uploads
    requestHeader [Host]: wtswc-product-data.oss-cn-hangzhou.aliyuncs.com
    requestHeader [Date]: Thu, 04 Nov 2021 02:48:19 GMT
    requestHeader [User-Agent]: aliyun-sdk-android/2.9.9(Linux/Android 5.1/HUAWEI%20TAG-AL00;HUAWEITAG-AL00)
    requestHeader [Content-Type]: application/zip
    requestHeader [x-oss-security-token]: 
    requestHeader [Authorization]: OSS LTAIJKWpRxag8lpb:WR8KOpXrrVp4r1jlQwiWJjf6GPw=
2021-11-04 10:48:19.216 7647-11653/? D/Posix: [Posix_connect Debug]Process ? :443 
2021-11-04 10:48:19.229 7647-11652/? D/OSS-Android-SDK: [Debug]: request method = POST
2021-11-04 10:48:19.243 7647-11652/? I/System.out: [CDS][DNS] getAllByNameImpl netId = 0
2021-11-04 10:48:19.243 7647-11652/? D/libc-netbsd: [getaddrinfo]: mtk hostname=wtswc-product-data.oss-cn-hangzhou.aliyuncs.com; servname=(null); cache_mode=(null), netid=0; mark=0
2021-11-04 10:48:19.243 7647-11652/? D/libc-netbsd: getaddrinfo( app_uid:10106
2021-11-04 10:48:19.243 7647-11652/? D/libc-netbsd: getaddrinfo() uid prop:
2021-11-04 10:48:19.243 7647-11652/? D/libc-netbsd: getaddrinfo() getuid():10106
2021-11-04 10:48:19.243 7647-11652/? D/libc-netbsd: [getaddrinfo]: mtk ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
2021-11-04 10:48:19.243 7647-11652/? D/libc-netbsd: [getaddrinfo]: mtk hostname=wtswc-product-data.oss-cn-hangzhou.aliyuncs.com; servname=(null); cache_mode=(null), netid=0; mark=0
2021-11-04 10:48:19.243 7647-11652/? D/libc-netbsd: getaddrinfo( app_uid:10106
2021-11-04 10:48:19.243 7647-11652/? D/libc-netbsd: getaddrinfo() uid prop:
2021-11-04 10:48:19.243 7647-11652/? D/libc-netbsd: getaddrinfo() getuid():10106
2021-11-04 10:48:19.243 7647-11652/? D/libc-netbsd: [getaddrinfo]: mtk ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=0
2021-11-04 10:48:19.361 7647-11653/? I/System.out: [socket][/10.208.241.71:57919] connected
2021-11-04 10:48:19.362 7647-11653/? D/libc-netbsd: [getaddrinfo]: mtk hostname=203.107.1.1; servname=(null); cache_mode=(null), netid=0; mark=0
2021-11-04 10:48:19.362 7647-11653/? D/libc-netbsd: getaddrinfo( app_uid:10106
2021-11-04 10:48:19.362 7647-11653/? D/libc-netbsd: getaddrinfo() uid prop:
2021-11-04 10:48:19.362 7647-11653/? D/libc-netbsd: getaddrinfo() getuid():10106
2021-11-04 10:48:19.362 7647-11653/? D/libc-netbsd: [getaddrinfo]: mtk ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
2021-11-04 10:48:19.362 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 NativeCrypto_SSL_do_handshake fd=0x7f682faff4 shc=0x7f682faff8 timeout_millis=10000 client_mode=1 npn=0x0
2021-11-04 10:48:19.362 7647-11653/? D/NativeCrypto: doing handshake ++
2021-11-04 10:48:19.362 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback where=0x10 ret=1
2021-11-04 10:48:19.362 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 handshake start in UNKWN  before/connect initialization
2021-11-04 10:48:19.362 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback calling handshakeCompleted
2021-11-04 10:48:19.362 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback completed
2021-11-04 10:48:19.362 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback where=0x1001 ret=1
2021-11-04 10:48:19.362 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 SSL_connect:UNKWN  before/connect initialization
2021-11-04 10:48:19.362 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback ignored
2021-11-04 10:48:19.362 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback where=0x1001 ret=1
2021-11-04 10:48:19.362 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 SSL_connect:23WCHA SSLv2/v3 write client hello A
2021-11-04 10:48:19.362 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback ignored
2021-11-04 10:48:19.362 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback where=0x1002 ret=-1
2021-11-04 10:48:19.362 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 SSL_connect:error exit in 23RSHA SSLv2/v3 read server hello A
2021-11-04 10:48:19.362 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback ignored
2021-11-04 10:48:19.362 7647-11653/? D/NativeCrypto: doing handshake -- ret=-1
2021-11-04 10:48:19.362 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 NativeCrypto_SSL_do_handshake ret=-1 errno=11 sslError=2 timeout_millis=10000
2021-11-04 10:48:19.384 7647-11652/? D/libc-netbsd: getaddrinfo: wtswc-product-data.oss-cn-hangzhou.aliyuncs.com get result from proxy >>
2021-11-04 10:48:19.385 7647-11652/? I/System.out: propertyValue:true
2021-11-04 10:48:19.387 7647-11652/? I/System.out: [CDS]rx timeout:360000
2021-11-04 10:48:19.387 7647-11652/? I/System.out: [socket][5] connection wtswc-product-data.oss-cn-hangzhou.aliyuncs.com/47.110.23.50:80;LocalPort=47098(360000)
2021-11-04 10:48:19.387 7647-11652/? I/System.out: [CDS]connect[wtswc-product-data.oss-cn-hangzhou.aliyuncs.com/47.110.23.50:80] tm:360
2021-11-04 10:48:19.388 7647-11652/? D/Posix: [Posix_connect Debug]Process ? :80 
2021-11-04 10:48:19.389 7647-11652/? I/System.out: [socket][/10.208.241.71:47098] connected
2021-11-04 10:48:19.404 7647-11652/? I/System.out: [CDS]rx timeout:360000
2021-11-04 10:48:19.413 7647-11653/? D/NativeCrypto: doing handshake ++
2021-11-04 10:48:19.413 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback where=0x1001 ret=1
2021-11-04 10:48:19.413 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 SSL_connect:3RSH_A SSLv3 read server hello A
2021-11-04 10:48:19.413 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback ignored
2021-11-04 10:48:19.414 7647-11653/? E/NativeCrypto: ssl=0x7f6a5d3980 cert_verify_callback x509_store_ctx=0x7f682fac68 arg=0x0
2021-11-04 10:48:19.414 7647-11653/? E/NativeCrypto: ssl=0x7f6a5d3980 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
2021-11-04 10:48:19.438 7647-11652/? D/OSS-Android-SDK: [Debug]: response:---------------------
    response code: 400 for url: http://wtswc-product-data.oss-cn-hangzhou.aliyuncs.com/wc_data_zip/2021-11-04/zip/07d748b83a0b0729d9b5b9b36e3c9f6b.zip?uploads
    responseHeader [connection]: close
    responseHeader [content-length]: 15
    responseHeader [content-type]: text/html
    responseHeader [date]: Thu, 4 Nov 2021 02:48:19 GMT
2021-11-04 10:48:19.447 7647-11652/? I/System.out: [CDS]close[47098]
2021-11-04 10:48:19.450 7647-11652/? D/OSS-Android-SDK: [Debug]: errorMessage  ：  
     400 Bad Request
2021-11-04 10:48:19.454 7647-11651/? W/SyncOssUpload: upload file to OSS failure.
2021-11-04 10:48:19.455 7647-11651/? W/System.err: com.alibaba.sdk.android.oss.ClientException: Unexpected token (position:TEXT 400 Bad Request@1:16 in java.io.InputStreamReader@21113126) 
2021-11-04 10:48:19.455 7647-11651/? W/System.err: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT 400 Bad Request@1:16 in java.io.InputStreamReader@21113126) 
2021-11-04 10:48:19.455 7647-11651/? W/System.err:     at com.alibaba.sdk.android.oss.internal.ResponseParsers.parseResponseErrorXML(ResponseParsers.java:850)
2021-11-04 10:48:19.455 7647-11651/? W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:218)
2021-11-04 10:48:19.455 7647-11651/? W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:47)
2021-11-04 10:48:19.455 7647-11651/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
2021-11-04 10:48:19.455 7647-11651/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
2021-11-04 10:48:19.455 7647-11651/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
2021-11-04 10:48:19.455 7647-11651/? W/System.err:     at java.lang.Thread.run(Thread.java:818)
2021-11-04 10:48:19.455 7647-11651/? W/System.err: Caused by: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT 400 Bad Request@1:16 in java.io.InputStreamReader@21113126) 
2021-11-04 10:48:19.455 7647-11651/? W/System.err:     at org.kxml2.io.KXmlParser.next(KXmlParser.java:432)
2021-11-04 10:48:19.455 7647-11651/? W/System.err:     at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
2021-11-04 10:48:19.455 7647-11651/? W/System.err:     at com.alibaba.sdk.android.oss.internal.ResponseParsers.parseResponseErrorXML(ResponseParsers.java:841)
2021-11-04 10:48:19.455 7647-11651/? W/System.err: 	... 6 more
2021-11-04 10:48:19.457 7647-11651/? W/SyncOssUpload: client Exception Unexpected token (position:TEXT 400 Bad Request@1:16 in java.io.InputStreamReader@21113126) 
    org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT 400 Bad Request@1:16 in java.io.InputStreamReader@21113126)  
2021-11-04 10:48:19.465 7647-11549/? D/OpenGLRenderer: Flushing caches (mode 0)
2021-11-04 10:48:19.466 7647-11549/? D/Surface: Surface::disconnect(this=0x7f82635400,api=1)
2021-11-04 10:48:19.466 7647-11549/? D/GraphicBuffer: unregister, handle(0x7f6a81d100) (w:736 h:466 s:736 f:0x1 u:0x000b00)
2021-11-04 10:48:19.467 7647-11549/? D/GraphicBuffer: unregister, handle(0x7f690d48e0) (w:736 h:466 s:736 f:0x1 u:0x000b00)
2021-11-04 10:48:19.467 7647-11549/? D/GraphicBuffer: unregister, handle(0x7f690d4f20) (w:736 h:466 s:736 f:0x1 u:0x000b00)
2021-11-04 10:48:19.468 7647-11549/? D/OpenGLRenderer: Flushing caches (mode 0)
2021-11-04 10:48:19.476 7647-7647/? D/Dialog: dismissDialog
2021-11-04 10:48:19.554 7647-7647/? W/Resources: Converting to string: TypedValue{t=0x1/d=0x7f0f01db a=-1 r=0x7f0f01db}
2021-11-04 10:48:19.560 7647-7647/? W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=5 r=0x7f08013e}
2021-11-04 10:48:19.560 7647-7647/? W/Resources: Converting to string: TypedValue{t=0x5/d=0xc01 a=5 r=0x7f060086}
2021-11-04 10:48:19.560 7647-7647/? W/Resources: Converting to string: TypedValue{t=0x5/d=0xe01 a=5 r=0x7f060087}
2021-11-04 10:48:19.560 7647-7647/? W/Resources: Converting to string: TypedValue{t=0x5/d=0xc01 a=5 r=0x7f060086}
2021-11-04 10:48:19.560 7647-7647/? W/Resources: Converting to string: TypedValue{t=0x5/d=0xe01 a=5 r=0x7f060087}
2021-11-04 10:48:19.572 7647-7647/? W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=5 r=0x7f08013d}
2021-11-04 10:48:19.573 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 cert_verify_callback => 1
2021-11-04 10:48:19.573 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback where=0x1001 ret=1
2021-11-04 10:48:19.573 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 SSL_connect:3RSC_A SSLv3 read server certificate A
2021-11-04 10:48:19.573 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback ignored
2021-11-04 10:48:19.574 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback where=0x1001 ret=1
2021-11-04 10:48:19.574 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 SSL_connect:3RSKEA SSLv3 read server key exchange A
2021-11-04 10:48:19.574 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback ignored
2021-11-04 10:48:19.574 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback where=0x1001 ret=1
2021-11-04 10:48:19.574 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 SSL_connect:3RSD_A SSLv3 read server done A
2021-11-04 10:48:19.574 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback ignored
2021-11-04 10:48:19.594 7647-7647/? W/Resources: Converting to string: TypedValue{t=0x1/d=0x7f0f01db a=-1 r=0x7f0f01db}
2021-11-04 10:48:19.594 7647-7647/? W/Resources: Converting to string: TypedValue{t=0x5/d=0xc01 a=5 r=0x7f060086}
2021-11-04 10:48:19.594 7647-7647/? W/Resources: Converting to string: TypedValue{t=0x5/d=0xc01 a=5 r=0x7f060086}
2021-11-04 10:48:19.594 7647-7647/? W/Resources: Converting to string: TypedValue{t=0x5/d=0xffffff00 a=5 r=0x7f060085}
2021-11-04 10:48:19.610 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback where=0x1001 ret=1
2021-11-04 10:48:19.610 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 SSL_connect:3WCKEA SSLv3 write client key exchange A
2021-11-04 10:48:19.610 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback ignored
2021-11-04 10:48:19.611 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback where=0x1001 ret=1
2021-11-04 10:48:19.611 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 SSL_connect:3WCCSA SSLv3 write change cipher spec A
2021-11-04 10:48:19.611 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback ignored
2021-11-04 10:48:19.611 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback where=0x1001 ret=1
2021-11-04 10:48:19.611 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 SSL_connect:3WFINA SSLv3 write finished A
2021-11-04 10:48:19.611 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback ignored
2021-11-04 10:48:19.611 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback where=0x1001 ret=1
2021-11-04 10:48:19.611 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 SSL_connect:3FLUSH SSLv3 flush data
2021-11-04 10:48:19.611 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback ignored
2021-11-04 10:48:19.611 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback where=0x1002 ret=-1
2021-11-04 10:48:19.611 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 SSL_connect:error exit in UNKWN  SSLv3 read server session ticket A
2021-11-04 10:48:19.611 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback ignored
2021-11-04 10:48:19.611 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback where=0x1002 ret=-1
2021-11-04 10:48:19.611 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 SSL_connect:error exit in UNKWN  SSLv3 read server session ticket A
2021-11-04 10:48:19.611 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback ignored
2021-11-04 10:48:19.611 7647-11653/? D/NativeCrypto: doing handshake -- ret=-1
2021-11-04 10:48:19.611 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 NativeCrypto_SSL_do_handshake ret=-1 errno=11 sslError=2 timeout_millis=10000
2021-11-04 10:48:19.627 7647-7647/? V/InputMethodManager: onWindowFocus: null softInputMode=32 first=false flags=#81810180
2021-11-04 10:48:19.627 7647-7647/? V/InputMethodManager: START INPUT: com.android.internal.policy.impl.PhoneWindow$DecorView{276661a3 V.E..... R....... 0,0-720,1280} ic=null tba=android.view.inputmethod.EditorInfo@3894b429 controlFlags=#100
2021-11-04 10:48:19.671 7647-11653/? D/NativeCrypto: doing handshake ++
2021-11-04 10:48:19.671 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback where=0x1001 ret=1
2021-11-04 10:48:19.671 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 SSL_connect:UNKWN  SSLv3 read server session ticket A
2021-11-04 10:48:19.671 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback ignored
2021-11-04 10:48:19.671 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback where=0x1001 ret=1
2021-11-04 10:48:19.671 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 SSL_connect:3RFINA SSLv3 read finished A
2021-11-04 10:48:19.671 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback ignored
2021-11-04 10:48:19.671 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback where=0x20 ret=1
2021-11-04 10:48:19.671 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 handshake done in SSLOK  SSL negotiation finished successfully
2021-11-04 10:48:19.671 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback calling handshakeCompleted
2021-11-04 10:48:19.671 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback completed
2021-11-04 10:48:19.671 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback where=0x1002 ret=1
2021-11-04 10:48:19.671 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 SSL_connect:ok exit in SSLOK  SSL negotiation finished successfully
2021-11-04 10:48:19.671 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 info_callback ignored
2021-11-04 10:48:19.671 7647-11653/? D/NativeCrypto: doing handshake -- ret=1
2021-11-04 10:48:19.671 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 NativeCrypto_SSL_get_certificate => NULL
2021-11-04 10:48:19.671 7647-11653/? I/System.out: gba_cipher_suite:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
2021-11-04 10:48:19.672 7647-11653/? I/System.out: [CDS]SO_SND_TIMEOUT:0
2021-11-04 10:48:19.672 7647-11653/? I/System.out: [OkHttp] sendRequest>>
2021-11-04 10:48:19.672 7647-11653/? I/System.out: [OkHttp] sendRequest<<
2021-11-04 10:48:19.672 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 sslWrite buf=0x7f7b45f000 len=233 write_timeout_millis=0
2021-11-04 10:48:19.673 7647-11653/? D/NativeCrypto: ssl=0x7f6a5d3980 sslRead buf=0x7f7b45f000 len=2048,timeo=10000
2021-11-04 10:48:19.780 7647-11653/? D/OSS-Android-SDK: [Debug]: [httpdnsmini] - ips:["47.110.23.50"]
2021-11-04 10:48:19.781 7647-11653/? D/OSS-Android-SDK: [Debug]: [httpdnsmini] - resolve result:[hostName=wtswc-product-data.oss-cn-hangzhou.aliyuncs.com, ip=47.110.23.50, ttl=22, queryTime=1635994099]
2021-11-04 10:48:24.928 7647-7647/? D/MessageJobService: onCreate: 
2021-11-04 10:48:24.932 7647-7647/? D/MessageJobService: onStartJob: 
2021-11-04 10:48:24.927 7647-7647/? D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@112ca54f className=?.alive.jobservice.MessageJobService packageName=? intent=null}
2021-11-04 10:48:24.951 7647-7647/? D/MessageJobService: onDestroy: 
2021-11-04 10:48:24.949 7647-7647/? D/ActivityThread: SVC-Destroying service: ?.alive.jobservice.MessageJobService@147aa4dc

**Comment by wushuai1415** [comment]
每次上传都会报这个错吗

**Comment by Rongrkang** [comment]
> 每次上传都会报这个错吗

这个手机每次都是的，其他的手机是好的，但是有些手机有时是有时不是很少这种情况

**Comment by wushuai1415** [comment]
> > 每次上传都会报这个错吗
> 
> 这个手机每次都是的，其他的手机是好的，但是有些手机有时是有时不是很少这种情况

提个工单查一下吧，这个url看着没什么问题，不知道后端为什么会返回400，而且这个400看着也不像是oss返回的，oss返回的错误都是xml结构的，这个400也不知道是哪里返回的，你把http改成https试试可不可以

**Comment by Rongrkang** [comment]
> > > 每次上传都会报这个错吗
> > 
> > 
> > 这个手机每次都是的，其他的手机是好的，但是有些手机有时是有时不是很少这种情况
> 
> 提个工单查一下吧，这个url看着没什么问题，不知道后端为什么会返回400，而且这个400看着也不像是oss返回的，oss返回的错误都是xml结构的，这个400也不知道是哪里返回的，你把http改成https试试可不可以

那个手机改成https就好了
