### ISSUE TITLE
升级值1.6.5后闪退

### ISSUE THREAD

**Issue by XianLiangZou** [aliyun/aliyun-oss-android-sdk#412]
升级前功能正常，升级后出现accessKeyId为null
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
                                                    	at com.alibaba.sdk.android.oss.common.auth.OSSPlainTextAKSKCredentialProvider.<init>(OSSPlainTextAKSKCredentialProvider.java:21)
                                                    	at com.alibaba.sdk.android.vod.upload.model.OSSConfig.getProvider(OSSConfig.java:92)
                                                    	at com.alibaba.sdk.android.vod.upload.internal.ResumableUploaderImpl.asycResumableUpload(ResumableUploaderImpl.java:164)
                                                    	at com.alibaba.sdk.android.vod.upload.internal.ResumableUploaderImpl.access$100(ResumableUploaderImpl.java:51)
                                                    	at com.alibaba.sdk.android.vod.upload.internal.ResumableUploaderImpl$1.run(ResumableUploaderImpl.java:155)
                                                    	at android.os.Handler.handleCallback(Handler.java:900)
                                                    	at android.os.Handler.dispatchMessage(Handler.java:103)
                                                    	at android.os.Looper.loop(Looper.java:219)
                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by wlll129** [comment]
原因是vod那边初始化OSSPlainTextAKSKCredentialProvider的参数为null，这个不是oss的问题需要那边看下

**Comment by wlll129** [comment]
原因是vod那边初始化OSSPlainTextAKSKCredentialProvider的参数为null，这个不是oss的问题需要那边看下
