### ISSUE TITLE
已添加混淆代码，但是混淆后上传失败！日志如下，很急！！！

### ISSUE THREAD

**Issue by ZengMingLove** [aliyun/aliyun-oss-android-sdk#72]
java.lang.IllegalStateException: Compute signature failed!
    at com.alibaba.sdk.android.oss.common.utils.OSSUtils.sign(OSSUtils.java:319)
    at com.alibaba.sdk.android.oss.common.utils.OSSUtils.signRequest(OSSUtils.java:560)
    at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:158)
    at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:44)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Stub!
    at org.apache.a.a.a.a.a(Base64.java:8)
    at com.alibaba.sdk.android.oss.common.utils.BinaryUtil.toBase64String(BinaryUtil.java:21)
    at com.alibaba.sdk.android.oss.common.auth.HmacSHA1Signature.computeSignature(HmacSHA1Signature.java:47)
    at com.alibaba.sdk.android.oss.common.utils.OSSUtils.sign(OSSUtils.java:316)
	... 7 more
java.lang.IllegalStateException: Compute signature failed!
    at com.alibaba.sdk.android.oss.common.utils.OSSUtils.sign(OSSUtils.java:319)
    at com.alibaba.sdk.android.oss.common.utils.OSSUtils.signRequest(OSSUtils.java:560)
    at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:158)
    at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:287)
    at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:44)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Stub!
    at org.apache.a.a.a.a.a(Base64.java:8)
    at com.alibaba.sdk.android.oss.common.utils.BinaryUtil.toBase64String(BinaryUtil.java:21)
    at com.alibaba.sdk.android.oss.common.auth.HmacSHA1Signature.computeSignature(HmacSHA1Signature.java:47)
    at com.alibaba.sdk.android.oss.common.utils.OSSUtils.sign(OSSUtils.java:316)
	... 8 more
com.alibaba.sdk.android.oss.ClientException: Compute signature failed!
[ErrorMessage]: Compute signature failed!
    at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:241)
    at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:287)
    at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:287)
    at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:44)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Compute signature failed!
    at com.alibaba.sdk.android.oss.common.utils.OSSUtils.sign(OSSUtils.java:319)
    at com.alibaba.sdk.android.oss.common.utils.OSSUtils.signRequest(OSSUtils.java:560)
    at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:158)
	... 7 more
Caused by: java.lang.RuntimeException: Stub!
    at org.apache.a.a.a.a.a(Base64.java:8)
    at com.alibaba.sdk.android.oss.common.utils.BinaryUtil.toBase64String(BinaryUtil.java:21)
    at com.alibaba.sdk.android.oss.common.auth.HmacSHA1Signature.computeSignature(HmacSHA1Signature.java:47)
    at com.alibaba.sdk.android.oss.common.utils.OSSUtils.sign(OSSUtils.java:316)
	... 9 more

**Comment by 1019272778** [comment]
@ZengMingLove 可以参见如下内容
http://blog.csdn.net/disneylu/article/details/53391187
