### ISSUE TITLE
异常崩溃

### ISSUE THREAD

**Issue by CharlesZqikai** [aliyun/aliyun-oss-android-sdk#97]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.NetworkInfo.getTypeName()' on a null object reference
at com.alibaba.sdk.android.oss.common.OSSLogToFileUtils$WriteCall.setBaseInfo(OSSLogToFileUtils.java:359)
at com.alibaba.sdk.android.oss.common.OSSLogToFileUtils$WriteCall.run(OSSLogToFileUtils.java:326)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)

**Comment by 1019272778** [comment]
@CharlesZqikai 可以升级到最新的版本。already fix

**Comment by CharlesZqikai** [comment]
compile 'com.aliyun.dpa:oss-android-sdk:2.4.4'  我目前的版本号

**Comment by 1019272778** [comment]
可以升级到最新的版本。用compile 'com.aliyun.dpa:oss-android-sdk:+'的方式。
